[tools]
elixir = "1.18.4"
erlang = "28.1"
pandoc = "3.3"
vale = "3.9.3"
flyctl = "0.3.91"

[hooks]
postinstall = "mise run install"

[alias]
pandoc = "asdf:https://github.com/Fbrisset/asdf-pandoc"
vale = "asdf:https://github.com/pdemagny/asdf-vale"

[env]
_.file = ".env.json"

[settings.sops]
age_key_file = "~/.config/mise/age-pepicrft.txt"
