service: website
image: pepicrft/website
servers:
  - 5.75.170.190
registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: amd64
  remote: ssh://root@5.75.170.190
volumes:
  - "/opt/website/db:/app/db/"
env:
  secret:
    - SECRET_KEY_BASE
    - MIX_ENV
proxy:
  app_port: 8080
  ssl: true
  host: pepicrft.me
  healthcheck:
    interval: 3
    path: /
    timeout: 3
