name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Fly
    runs-on: docker
    steps:
      - uses: actions/checkout@v3
      - run: curl https://mise.run | sh
      - run: curl -L https://fly.io/install.sh | sh
      - run: /root/.fly/bin/flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
