name: Website
on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: pepicrftme-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: "1"
  MISE_SOPS_AGE_KEY: ${{ secrets.MISE_SOPS_AGE_KEY }}
  MISE_GITHUB_TOKEN: ${{ secrets.PEPICRFT_GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PEPICRFT_GITHUB_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: git config --global user.email "website@pepicrft.me"
      - run: git config --global user.name "website"
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mise run install
      - run: mise run lint:spell
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: git config --global user.email "website@pepicrft.me"
      - run: git config --global user.name "website"
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mise run install
      - run: mise run build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: git config --global user.email "website@pepicrft.me"
      - run: git config --global user.name "website"
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - run: mix deps.get
      - run: mix test
